### ISSUE TITLE
Root pointer

### ISSUE THREAD

**Issue by mikesimons** [mikesimons/templateer#4]
Where templateer is operating on a subset of a larger configuration file it may be handy to be able to change where in the tree `@data` is from.

Consider data.yaml

```
metadata:
  somestuff: hello

config:
  nested:
    subnest:
      useful_data1: 1
      useful_data2: 2
```

Where a template only operates on `config -> nested -> subnest` it would make sense for `@data` to only contain the contents of that.

A cli flag, `--root` of a dotted or slashed path type notation would make most sense I think.
Examples:
`templateer --root config.nested.subnest data.yaml sometemplate.erb`
or
`templateer --root config/nested/subnest data.yaml sometemplate.erb`
