### ISSUE TITLE
Command line data merge

### ISSUE THREAD

**Issue by mikesimons** [mikesimons/templateer#5]
Would be useful to be able to override / provide additional parameters that are merged in to `@data` from the command line.

e.g. data.yaml

```
item1:
  sub_item1: x
item2:
  sub_item2: y
```

`templateer --data item1.sub_item2=z data.yml -`

would yield `@data`:

```
item1:
  sub_item1: x
  sub_item2: z
item2:
  sub_item2: y
```

Need to consider the following scenarios:
`--data some_bool=true` should be `Boolean`, not the string `true`.
`--data some_int=1` should be `Numeric`, not the string `1`
`--data some_array[]=append` should append the string `append` to `some_array`
`--data some_array=[1,2,3]` should be an `Array` type containing `Numeric` types `1`, `2` & `3`
